# Generated by Django 4.0.3 on 2024-03-21 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('제목', models.CharField(max_length=255)),
                ('매물종류', models.CharField(max_length=255)),
                ('거래종류', models.CharField(max_length=255)),
                ('매매가', models.CharField(max_length=255)),
                ('월세', models.CharField(blank=True, max_length=255)),
                ('테마', models.CharField(max_length=255)),
                ('공급면적', models.CharField(max_length=255)),
                ('공면가격', models.CharField(blank=True, max_length=255)),
                ('전용면적', models.CharField(max_length=255)),
                ('전면가격', models.CharField(blank=True, max_length=255)),
                ('방향', models.CharField(blank=True, max_length=255)),
                ('해당층', models.CharField(blank=True, max_length=255)),
                ('전체층', models.CharField(blank=True, max_length=255)),
                ('난방', models.CharField(blank=True, max_length=255)),
                ('주차', models.CharField(blank=True, max_length=255)),
                ('주차비', models.CharField(blank=True, max_length=255)),
                ('입주일', models.CharField(blank=True, max_length=255)),
                ('사용승인일', models.CharField(blank=True, max_length=255)),
                ('업로드_시간', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('이미지', models.ImageField(upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mom.property')),
            ],
        ),
    ]
