# Generated by Django 4.1.7 on 2025-02-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='호수',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
