# Generated by Django 4.0.3 on 2024-03-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mom', '0002_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegroup',
            name='이미지',
            field=models.ImageField(upload_to='images/20240321-185854'),
        ),
    ]
