# Generated by Django 4.0.3 on 2024-03-21 19:16

from django.db import migrations, models
import mom.models


class Migration(migrations.Migration):

    dependencies = [
        ('mom', '0003_alter_imagegroup_이미지'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegroup',
            name='이미지',
            field=models.ImageField(upload_to=mom.models.get_custom_filename),
        ),
    ]
