# Generated by Django 4.0.3 on 2024-03-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mom', '0004_alter_imagegroup_이미지'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='property',
            name='강력추천',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='급매',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='신축',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='인기',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='저렴',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='즉시입주',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='추천',
            field=models.BooleanField(default=False),
        ),
    ]
