# Generated by Django 4.0.3 on 2024-04-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mom', '0007_property_내용'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='매매가억',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
