# Generated by Django 4.0.3 on 2024-04-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mom', '0008_property_매매가억'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='공면치환',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='전면치환',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
