# Generated by Django 4.0.3 on 2024-04-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mom', '0009_property_공면치환_property_전면치환'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='지역',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
